language: node_js
node_js:
  - "6.9.1"
env:
  - NODE_ENV=travis
install:
  - npm install
  - gulp build-release
branches:
  only:
    - master
cache:
  apt : true
  directories:
    - node_modules
notifications:
  email:
      - kulkarni.mak172@gmail.com
